// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Television_API.Data;

#nullable disable

namespace Television_API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250905154801_changeActorModelNullableBirth")]
    partial class changeActorModelNullableBirth
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.8");

            modelBuilder.Entity("TVShowActor", b =>
                {
                    b.Property<int>("ActorId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TVShowId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ActorId", "TVShowId");

                    b.HasIndex("TVShowId");

                    b.ToTable("TVShowActor");
                });

            modelBuilder.Entity("Television_API.Models.Actor", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("birthday")
                        .HasColumnType("TEXT");

                    b.Property<string>("deathday")
                        .HasColumnType("TEXT");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("Actors");
                });

            modelBuilder.Entity("Television_API.Models.Episode", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("airDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("episode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("season")
                        .HasColumnType("INTEGER");

                    b.Property<int>("tvShowId")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.HasIndex("tvShowId");

                    b.ToTable("Episodes");
                });

            modelBuilder.Entity("Television_API.Models.TVShow", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.PrimitiveCollection<string>("genres")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("isOngoing")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("startDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("TVShows");
                });

            modelBuilder.Entity("TVShowActor", b =>
                {
                    b.HasOne("Television_API.Models.Actor", null)
                        .WithMany()
                        .HasForeignKey("ActorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Television_API.Models.TVShow", null)
                        .WithMany()
                        .HasForeignKey("TVShowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Television_API.Models.Episode", b =>
                {
                    b.HasOne("Television_API.Models.TVShow", "tvShow")
                        .WithMany("episodes")
                        .HasForeignKey("tvShowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("tvShow");
                });

            modelBuilder.Entity("Television_API.Models.TVShow", b =>
                {
                    b.Navigation("episodes");
                });
#pragma warning restore 612, 618
        }
    }
}
